<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <Configuration>Release</Configuration>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\Release\net9.0\results\EasyTrace.Benchmarks.MemoryBenchmark-report-github.md" />
    <Content Include="bin\Release\net9.0\results\EasyTrace.Benchmarks.MemoryBenchmark-report.html" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EasyTrace\EasyTrace.csproj" />
  </ItemGroup>
</Project>